# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJct4rz01YTj7sV_Nhu6Wwvr3Lb8bRv5
"""

import random

t = random.randint(0,100)
h = random.randint(0,100)

print("Temperature is = ",t)
print("Humidity is = ",h)

if t >60 and h > 60:
    print("alarm ON : It is to be risky")
elif t > 60 and h < 60:
    print("alarm ON : It is to be high temperature")
else:
    print("alarm OFF")