# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-aoMOenOnOXZE9-ZKmPufpqcVAShLQ8
"""

import random
temperature = random.randint(0,200)
humidity = random.randint(0,150)
print("Temperature value = ",temperature)
print("Humidity Value = ",humidity)
if temperature > 80 and humidity > 70:
    print("alarm ON : Hazardous Predicted")
elif temperature > 80 and humidity < 70:
    print("alarm ON : High Temperature")
else:
    print("alarm OFF")